angular.module("app",['ngRoute'])
.config(['$routeProvider', function($routeProvider){
    $routeProvider.
    when('/main',
     {
      templateUrl:'templates/main.html',
      controller:'MainCtrl'
     })
	.when('/about',
	 {
      templateUrl:'templates/about.html',
      controller:'AboutCtrl'
     })
	.when('/activities',
     {
      templateUrl:'templates/activities.html',
      controller:'ActivitiesCtrl'
     })
	.when('/contact',
     {
      templateUrl:'templates/contact.html',
      controller:'ContactCtrl'
     })
    .otherwise({redirectTo:'/main'})
  }])
